Repository crowi/crowi, pull requests merged in 2019-08, with the labels that each got.

#508 Fix: TS compile error when run with FILE_UPLOAD=aws
  local_modules/crowi-fileupload-aws/index.js
Labels: Bug

#521 Fix file resolving error
  lib/app.ts
  lib/util/search.ts
Labels: Bug

#522 Fix: error on emitting page update event when grant changed
  lib/models/page.ts
Labels: Bug

#527 Fix error on rename
  lib/models/page.ts
Labels: Bug

#528 Remove proxyquire because no longer used
  package-lock.json
  package.json
Labels: DEV Issue

#531 Separate login and register pages and update its style
  client/crowi.ts
  lib/controllers/login.ts
  lib/middlewares/loginRequired.ts
  lib/routes/login.ts
  package-lock.json
  package.json
  resource/css/_layout.scss
  resource/css/_page_list.scss
  resource/css/crowi.scss
  views/installer.html
  views/layout/layout.html
  views/login.html
  views/login/error.html
  views/me/auth/third-party.html
  views/register.html
Labels: Bug, Feature

#553 Tree shaking for icons
  .storybook/preview-head.html
  client/components/Admin/Navigation.tsx
  client/components/BookmarkButton.tsx
  client/components/Comment/CommentLists.tsx
  client/components/Common/Icon.stories.tsx
  client/components/Common/Icon.test.tsx
  client/components/Common/Icon.tsx
  client/components/Common/Icons.stories.tsx
  client/components/Common/Icons.tsx
  client/components/ExternalShare/SettingModal.tsx
  client/components/ExternalShare/ShareBox.tsx
  client/components/HeaderSearchBox/SearchForm.tsx
  client/components/HeaderSearchBox/SearchSuggest.tsx
  client/components/Notification/ModelAction/PageLikeNotification.tsx
  client/components/Notification/NotificationItem.tsx
  client/components/Notification/NotificationItemContent.tsx
  client/components/PageAlerts/PageAlert.tsx
  client/components/PageAttachment/Attachment.tsx
  client/components/PageAttachment/DeleteAttachmentModal.tsx
  client/components/PageHistory/Revision.tsx
  client/components/PageList/PageListMeta.tsx
  client/components/RenameTree/RenameTree.tsx
  client/components/SearchPage/SearchResult.tsx
  client/components/SearchPage/SearchToolbar.tsx
  package.json
  views/layout/2column.html
  views/layout/single.html
  views/page.html
  views/page_list.html
Labels: DEV Issue

#550 Fix: error activate invited
  README.md
  lib/models/user.ts
  public/logo/100x11_g.png
  public/logo/100x11_w.png
  public/logo/1600x1600-w-border-circle.png
  public/logo/2000x550-w-border.png
  public/logo/500w-inverse.png
  public/logo/500w.png
  public/logo/powered-by-crowi-inverse.png
  public/logo/powered-by-crowi-inverse@2x.png
  public/logo/powered-by-crowi.png
  public/logo/powered-by-crowi@2x.png
  resource/css/_layout.scss
  views/installer.html
  views/invited.html
  views/layout/2column.html
  views/layout/single.html
  views/login.html
  views/login/error.html
  views/me/auth/third-party.html
  views/register.html
Labels: Bug

#558 Update eslint and format some errors
  .eslintrc
  client/components/RenameTree/RenameTree.tsx
  client/crowi-admin.ts
  client/crowi-form.ts
  client/crowi.ts
  client/util/Crowi.ts
  client/util/CrowiRenderer.ts
  client/util/LangProcessor/Template.ts
  lib/crowi/index.ts
  lib/models/page.ts
  lib/service/notification.ts
  lib/util/search.ts
  package-lock.json
  package.json
Labels: DEV Issue

#560 Fix/mongo deprecation
  lib/crowi/index.ts
  lib/models/activity.ts
  lib/models/attachment.ts
  lib/models/backlink.ts
  lib/models/bookmark.ts
  lib/models/comment.ts
  lib/models/config.ts
  lib/models/notification.ts
  lib/models/page.ts
  lib/models/revision.ts
  lib/models/share.ts
  lib/util/search.ts
  test/models/activity.test.ts
  test/models/backlink.test.ts
  test/models/notification.test.ts
  test/models/page.test.ts
  test/models/share.test.ts
Labels: DEV Issue
