Repository crowi/crowi, pull requests merged in 2019-09, with the labels that each got.

#557 Fix: admin page bug
  client/components/Admin/App/AWSSettings.tsx
  client/components/Admin/TopPage.tsx
  docker-compose.development.yml
  lib/controllers/admin.ts
  lib/util/search.ts
  locales/en-US/translation.yml
  test/util/search.test.ts
Labels: Bug

#537 Update i18next
  package-lock.json
  package.json
Labels: DEV Issue, dependencies

#564 Introduce husky and lint staged
  .huskyrc
  .lintstagedrc
  package-lock.json
  package.json
Labels: DEV Issue

#565 Fix issue user icons aren't displayed on page list
  lib/models/page.ts
Labels: Bug

#567 Update tools
  package-lock.json
  package.json
  webpack/client/webpack.style.js
Labels: DEV Issue

#563 Fix issue admin notification form values and newly fetched values are not synced
  client/components/Admin/Notification/Instructions.tsx
  client/components/Admin/Notification/NotificationSettings.tsx
  client/hooks/useStateWithEffect.ts
Labels: Bug
